name: CI - CD


on:
  
  push:
    branches: [ "main" ]
  

  workflow_dispatch:


jobs:

  CI:
  
    runs-on: ubuntu-latest

   
    steps:
     
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
         
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./Dockerfile
          push: true
          tags: | 
            ninompit/ninompit/app-ezops:v1
            
     
   
    runs-on: ubuntu-latest
    steps:
    
     - uses: actions/checkout@v3
     - name: Build-image e BD
       run: docker-compose build

     - name: Create-DB
       run: docker-compose up
      # AWS Access Key ID
         aws-access-key-id: 
    # AWS Secret Access Key
         aws-secret-access-key: 
    # AWS Region
         aws-region: 
    # AWS Account ID
         aws-account-id: 
 
  
  
