name: CI - CD


on:
  
  push:
    branches: [ "main" ]
  

  workflow_dispatch:


jobs:

  CI:
  
    runs-on: ubuntu-latest

   
    steps:
     
      - uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_PWD}}
         
      - name: Build and push Docker images
        uses: docker/build-push-action@v3.0.0
        with:
          file: ./src/Dockerfile
          context: ./src
          push: true
          tags: |
            ninompit/app-ezops:latest
            ninompit/app-ezops:${{github.run_number}}
            
  CD: 
  
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
     - name: Docker pull from DockerHub
     - uses: actions/checkout@v3
       with:
         username: ec2-user
         key: ${{secrets.PRIVATE_KEY}}
         envs: GITHUB_SHA
         script: |
           docker login:
           docker pull: ninompit/app-ezops:${{github.run_number}}
           docker run -d --network ezops-network -p 27017:27017 --name mongodb -e MONGO_INITDB_ROOT_USERNAME=alexdevops -e MONGO_INITDB_ROOT_PASSWORD=alexdevops123 mongo 
           docker run -d -p 3000:3000 -e MONGODB_URI=mongodb+srv://alexdevops:alexdevops123@cluster0.onflfy5.mongodb.net/simple-chat --network ezops-network ninompit/app-ezops:${{github.run_number}}
 
            
     
   
    

  
  
